config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: 'home#index'

  resources :events, except: [:show] do
    member do
      get :invitation
      post :accept_invitation
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user

  has_many :registrations, dependent: :destroy
  has_many :invited_users, through: :registrations, source: :user

  scope :upcoming, -> { where(date_time: Time.now.utc..) }
  scope :past, -> { where(date_time: ...Time.now.utc) }

  validates :name, presence: true
  validates :date_time, presence: true
  validates :location, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/registration.rb
# frozen_string_literal: true

class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :user, uniqueness: { scope: :event, message: 'member can only be registered one time' }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :invited_events, through: :registrations, source: :event

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update destroy invitation accept_invitation]
  before_action :authenticate_user!

  def index
    @upcomming_events = current_user.events.upcoming.order(date_time: :asc)
    @past_events = current_user.events.past.order(date_time: :desc)
    @invited_events = current_user.invited_events.order(date_time: :asc)
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path, notice: I18n.t('events.created')
    else
      render :new, status: :internal_server_error
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: I18n.t('events.updated')
    else
      render :edit, status: :internal_server_error
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('events.destroyed')
  end

  def invitation
  end

  def accept_invitation
    registration = Registration.create(event: @event, user: current_user)
    if registration.persisted?
      render json: { success: true }
    else
      render json: { success: false, error: registration.errors.full_messages.join(', ') },
             status: :internal_server_error
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :date_time, :location, :capacity, :user_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
    redirect_to events_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/events/_event_box.html.erb
<div class="event-box card mb-4">
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <h3>
          <%= event.name %>
        </h3>
        <p>
          <%= event.description %>
        </p>
      </div>
      <div class="col-4">
        <div class="actions-container">
          <%= link_to edit_event_path(event), class: 'btn btn-primary', style: 'margin-right: 8px;' do %>
            <i class="fa-solid fa-pen"></i>
          <% end %>

          <%= button_to event_path(event), data: { confirm: "¿Estás seguro de borrar este evento?", turbo_confirm: "¿Estás seguro de borrar este evento?" }, method: :delete, class: 'btn btn-danger' do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
    <p>
      <i class="fa-regular fa-calendar"></i>

      <strong>
        Fecha:
      </strong>
      <%= event.date_time.strftime('%d/%m/%Y %H:%M') %>
    </p>
    <p>
      <i class="fa-solid fa-location-dot"></i>
      <strong>
        Ubicación:
      </strong>
      <%= event.location %>
    </p>
    <p>
      <strong>
        Capacidad:
      </strong>
      <%= event.capacity %>
    </p>

  </div>
</div>

app/views/events/_form.html.erb
<h3>
  <%= @event.persisted? ? 'Editar' : 'Crear' %> evento
</h3>

<%= form_with(model: @event, local: true, html: { class: 'needs-validation', novalidate: true, data: { controller: 'bootstrap-forms' } }) do |form| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Nombre", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      El evento debe tener un nombre
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción (opcional)", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date_time, "Fecha del evento", class: 'form-label' %>
    <%= form.datetime_field :date_time, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Debes proporcionar una fecha y hora válida.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :location, "Ubicación", class: 'form-label' %>
    <%= form.text_field :location, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Debes indicar el lugar ubicación.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :capacity, "Capacidad", class: 'form-label' %>
    <%= form.number_field :capacity, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Debes indicar la capacidad del evento.
    </div>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="mt-4 mb-3">
    <%= form.submit @event.persisted? ? 'Editar' : 'Crear', class: 'btn btn-primary w-100' %>
  </div>
<% end %>

<%= link_to 'Volver', events_path, class: 'btn btn-secondary w-100' %>

app/views/events/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-4">
    <%= render "form" %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-4 offset-md-8">
    <%= link_to new_event_path, class: 'btn btn-success w-100' do %>
      <i class="fa-solid fa-plus"></i>
      Añadir evento
    <% end %>
  </div>
</div>

<div class="accordion mt-4" id="accordionFlushExample">

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#invited-events" aria-expanded="true" aria-controls="invited-events">
        <strong>
          Eventos que me han invitado
        </strong>
      </button>
    </h2>
    <div id="invited-events" class="accordion-collapse collapse show" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <% if @invited_events.empty? %>
          <div class="text-center py-3">
            No hay eventos que mostrar en esta sección.
          </div>
        <% else %>
          <% @invited_events.each do |event| %>
            <%= render 'event_box', event: event %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        <strong>
          Eventos
        </strong>
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <% if @upcomming_events.empty? %>
          <div class="text-center py-3">
            Aún no has añadido ningún evento, puedes hacerlo en el botón de arriba.
          </div>
        <% else %>
          <% @upcomming_events.each do |event| %>
            <%= render 'event_box', event: event %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        <strong>
          Eventos pasados
        </strong>
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <% if @past_events.empty? %>
          <div class="text-center py-3">
            No hay eventos que mostrar en esta sección.
          </div>
        <% else %>
          <% @past_events.each do |event| %>
            <%= render 'event_box', event: event %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/events/invitation.html.erb
<div class="event-box card mb-4">
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <h3>
          Invitación a evento "<%= @event.name %>"
        </h3>
        <p>
          <%= @event.description %>
        </p>
      </div>
    </div>
    <p>

      <strong>
        Organizador
      </strong>
      <%= @event.user.full_name %>
    </p>
    <p>
      <i class="fa-regular fa-calendar"></i>

      <strong>
        Fecha:
      </strong>
      <%= @event.date_time.strftime('%d/%m/%Y %H:%M') %>
    </p>
    <p>
      <i class="fa-solid fa-location-dot"></i>
      <strong>
        Ubicación:
      </strong>
      <%= @event.location %>
    </p>
    <p>
      <strong>
        Capacidad:
      </strong>
      <%= @event.capacity %>
    </p>

    <div data-controller="hello">
      ¿Quieres aceptar la invitación a este evento?

      <input type="hidden" data-hello-target="event" value="<%= @event.id %>">

      <button type="button" 
        class="btn btn-success"
        data-action="click->hello#accept"
      >
        Si, quiero
      </button>
      <button type="button" class="btn btn-danger" data-action="click->hello#reject">Rechazar</button>
    </div>

  </div>
</div>

app/views/events/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-4">
    <h3>
      <%= @event.persisted? ? 'Editar' : 'Crear' %> evento
    </h3>

    <%= form_with(model: @event, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
      <% if @event.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
          <ul>
            <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :name, "Nombre", class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control', required: true %>
        <div class="invalid-feedback">
          El evento debe tener un nombre
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :description, "Descripción (opcional)", class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :date_time, "Fecha del evento", class: 'form-label' %>
        <%= form.datetime_field :date_time, class: 'form-control', required: true, min: (Date.today.beginning_of_day).strftime("%Y-%m-%dT%H:%M") %>        <div class="invalid-feedback">
          Debes proporcionar una fecha y hora válida.
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :location, "Ubicación", class: 'form-label' %>
        <%= form.text_field :location, class: 'form-control', required: true %>
        <div class="invalid-feedback">
          Debes indicar el lugar ubicación.
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :capacity, "Capacidad", class: 'form-label' %>
        <%= form.number_field :capacity, class: 'form-control', required: true %>
        <div class="invalid-feedback">
          Debes indicar la capacidad del evento.
        </div>
      </div>

      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="mt-4 mb-3">
        <%= form.submit 'Crear', class: 'btn btn-primary w-100' %>
      </div>
    <% end %>

    <%= link_to 'Volver', events_path, class: 'btn btn-secondary w-100' %>
  </div>
</div>

app/views/home/index.html.erb
<% unless current_user %>
  <div class="text-center pt-5">
    <div>
      <i class="fa-regular fa-face-smile-beam" style="font-size: 60px;"></i>
    </div>

    <div class="mt-4">
      Bienvenido, para comenzar a utilizar la aplicación es necesario que inicies sesión.
      <a href="<%= new_user_session_path %>">
        Iniciar sesión
      </a>
    </div>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="global-feedback-alert alert alert-primary text-center" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="global-feedback-alert alert alert-danger text-center" role="alert">
    <%= alert %>
  </div>
<% end %>

<% if alert || notice %>
  <script>
    setTimeout(() => {
      const alert = document.querySelector('.global-feedback-alert')
      if (alert){
        alert.classList.add('fade-out')
      }
    }, 5000);
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Events App Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if current_page?(events_path) %>" aria-current="page" href="<%= events_path %>">Inicio</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= 'active' if current_page?(edit_user_registration_path) %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user&.full_name %>
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Mi Perfil</a></li>
                <li>
                  <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if current_page?(new_user_session_path) %>" aria-current="page" href="<%= new_user_session_path %>"> Iniciar sesión </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/46a20aeafd.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>

    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>